"""tags

Revision ID: ed97d00cbdc6
Revises: 5a9db05110e4
Create Date: 2019-03-22 10:35:15.905433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed97d00cbdc6'
down_revision = '5a9db05110e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('tags', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'tags')
    # ### end Alembic commands ###
